### ISSUE TITLE
Trouble connection to UR10e with Machina-Bridge

### ISSUE THREAD

**Issue by baharmon** [RobotExMachina/Machina-Bridge#9]
**Issue**
I am having trouble connecting to my UR10e with Machina Bridge and I've run out of troubleshooting ideas so would like to ask for your advice. I have setup a wired network using an EdgeRouter X and it seems to be working, but Machina Bridge does not connect. I can ping the robot successfully. I've also tried testing the connection with SocketTest and Hercules. With Hercules I can ping the robot and connect on port 30004, but not port 7000 which gives a 10061 connection error. From this [UR TCP/IP documentation](https://www.universal-robots.com/articles/ur/remote-control-via-tcpip/) it seems like I should be using port 30004 for real time exchange. Is there anything useful in the debugging output from Machina Bridge? Any ideas would be most welcome. 
Thanks, Brendan

**Troubleshooting**
* Use 7zip to unarchive Machina-Bridge
* Run as administrator or regular user
* Try assigning static IPs or dynamic IPs
* Try a direct connection with static IP vs. a connection via router
* Add firewall exceptions on Windows and the router
* Disable Windows and router firewalls
* Try different ports
* Enable or disable remote control on the teach pendant
* Try a different router?

**Connection Error**
<img width="1920" alt="capture-1" src="https://user-images.githubusercontent.com/10392927/100946087-390a1e00-34c8-11eb-8277-b399ac62de3c.png">

**Network Traffic**
<img width="1121" alt="capture-4" src="https://user-images.githubusercontent.com/10392927/100946095-3c9da500-34c8-11eb-99dc-08c367c68b3c.png">

**Comment by garciadelcastillo** [comment]
Hi @baharmon , 
Machina uses a different method to communicate with the robot than the default ports you point to in the docs, so you will never be able to connect via 30004 for example (because it's already taken by the internal servers).
What Machina does is two things:
- It injects a program on the robot that starts a TCP client on it, using whichever port you type on the Bridge (7000 for example). 
- Then, it waits for that client to connect to a TCP server that the Bridge starts.

So something is failing: either the Bridge cannot upload the module to the UR robot, or once uploaded, it doesn't trigger and/or the initialization routine doesn't reach the Bridge. From the screenshots, it looks like it is the latter...

**Comment by garciadelcastillo** [comment]
Have you checked this? https://www.youtube.com/watch?v=WlxNqkk9Kz0&list=PLvxxYImPCApUffcv_KtdR-sQydA4O4CPH&index=8

**Comment by garciadelcastillo** [comment]
If you go to the robot's debug console, do you see a message saying "Started Machina driver"?

**Comment by baharmon** [comment]
Thanks for the quick reply. I did follow the youtube tutorial closely. No, I don't see the message `Started Machina driver` in Polyscope's log. Is that the right debugging console? Instead I get: 
```
C210A0: Socket is read-only when the robot is in local (Teach pendant) control
```

**Comment by baharmon** [comment]
Solved it. Thanks for your help. Just needed to switch to remote control after enable remote control mode in settings.

**Comment by garciadelcastillo** [comment]
Aha! Happy it worked :)
